language: objective-c
osx_image: xcode10.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftPusher.xcodeproj
  - IOS_FRAMEWORK_SCHEME="SwiftPusher-iOS"
  - MACOS_FRAMEWORK_SCHEME="SwiftPusher-macOS"
  - IOS_SDK=iphonesimulator12.2
  - MACOS_SDK=macosx10.14
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone XS" SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="$IOS_SDK"      RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=11.4,name=iPhone X"  SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="$IOS_SDK"      RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64"            SCHEME="$MACOS_FRAMEWORK_SCHEME"    SDK="$MACOS_SDK"    RUN_TESTS="YES" POD_LINT="NO"

before_install:
- rvm use $RVM_RUBY_VERSION

install:
- bundle install

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES build | xcpretty;
    fi

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f test_results/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
